package com.myapp.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-19T13:02:40.382+05:30
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://myapp.com/orders/", name = "orders")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Orders {

    @WebMethod(action = "http://myapp.com/orders/search")
    @WebResult(name = "OrdersList", targetNamespace = "http://myapp.com/orders/", partName = "ordersList")
    public OrderInfoWrapper search(

        @WebParam(partName = "productName", name = "ProductName", targetNamespace = "http://myapp.com/orders/")
        ProductNameWrapper productName
    );
}
